### ISSUE TITLE
What version Chrome can support the new PressureObserver interface?

### ISSUE THREAD

**Issue by Tang0770** [w3c/compute-pressure#113]
I use a Chrome 102 with the `#enable-experimental-web-platform-features` flag enabled, and  the former version ComputePressureObserver can be used normally.

But as the level1 document updates a new version PressureObserver interface, I could not use it in my Chrome and I wonder how could I use this and could you please update the README as I notice that the example in README is still a former version.

**Comment by kenchris** [comment]
We are currently working on implementing the new API shape but it requires some major refactorings so we are doing the work on a branch and then upstreaming in parallel. This is taking some time, but hopefully you should start seeing patches landing soon.

**Comment by Tang0770** [comment]
So do I have some method to find out if the new API is released? 

And I wonder whether the ComputePressureObserver will be abolished when the new API is released? If not, do I have anywhere to read the document for ComputePressureObserver API?

**Comment by kenchris** [comment]
This spec contains the latest API that will be implemented

**Comment by kenchris** [comment]
This is supported in Chrome now behind a flag
