### ISSUE TITLE
Can the permission be dropped? 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/compute-pressure#158]
The dependency on .requestPermission() seems less than ideal. As folks discussed at the recent Permissions workshop, APIs shoulder avoid asking for permission at all costs, and only do so when all other means of solving the problem have been exhausted. It seems like this API was designed as "permission first", and it seems fairly unlikely that users will understand what compute pressure is about. 

At least, it seems somewhat hand-wavy as to how one would articulate this to a user. 

The specifications speaks about video use cases and that would affect layout (e.g., hiding videos, etc.). Have the authors of this spec considered just dealing with the cases instead of having this low level API? Perhaps that might avoid the need to ask for permission at all.

**Comment by kenchris** [comment]
Chrome will not be using a permission for this, so we will remove this

**Comment by anssiko** [comment]
Addressed by https://github.com/w3c/compute-pressure/pull/166
