### ISSUE TITLE
Add an implementation-defined change threshold exceeded check

### ISSUE THREAD

**Issue by anssiko** [w3c/compute-pressure#176]
We've received [Dev Trial](https://chromestatus.com/feature/5597608644968448) feedback from a major ISV that the state changes between ["serious"](https://www.w3.org/TR/compute-pressure/#dom-pressurestate-serious) and ["fair"](https://www.w3.org/TR/compute-pressure/#dom-pressurestate-fair) [pressure states](https://www.w3.org/TR/compute-pressure/#dfn-pressure-states) are too rapid as illustrated below:

![cp-demo](https://user-images.githubusercontent.com/765510/215411760-a8b8042a-bbba-4c9e-b684-6962e909e622.png)

This suggests the spec should add an informative note that recommends implementers to add [hysteresis](https://en.wikipedia.org/wiki/Hysteresis#In_engineering) to the [notify pressure observers](https://www.w3.org/TR/compute-pressure/#dfn-notify-pressure-observers) algorithm and amend the algorithm steps accordingly to allow an implementation to bail out without notifying if the threshold has not been reached. This seems particularly important at the top-end of the range based on the feedback received.

Adding hysteresis in the implementation as opposed to in the JS logic would also further improve privacy by lowering the entropy of the overall system. This improvement could be noted in the [security and privacy considerations](https://www.w3.org/TR/compute-pressure/#security-and-privacy-considerations) section.

(The mathematical model is formalized as [Preisach model of hysteresis](https://en.wikipedia.org/wiki/Preisach_model_of_hysteresis) and is being used in various fields of science and engineering.)

**Comment by kenchris** [comment]
There was already the plan to add an average value for the last 10 seconds, 30 seconds and something like that, like the pressure stall information on linux has.

**Comment by kenchris** [comment]
Yes, I understand the point of this, but it speaks a bit against fine grained frequency (maybe that is fine), because spikes in utilization (boosting) is quite common. Only a high frequency allows you to catch such cases.

But I think adding the average also makes sense to know how it behaved over time, like last 10 sec, last minute and last 10 minutes. This should also be more efficient to calculate in the browser than in JS and we could make it opt in.

**Comment by anssiko** [comment]
As I understood it from this Dev Trial feedback, too frequent flip-flopping (e.g. once a second) between pressure states was the issue and the preference would be to have the native implementation smooth this out i.e. provide _less frequent_ change notifications. These changes might now trigger a user-visible UI change once a second unless web developers do filtering in JS which would feel wrong and I agree would be less performant. It should be said this is an edge case where the system is pushed to its limits.

Wouldn't it be better for (most?) mainstream use cases to remove the high-frequency spikes by default (similar to impulse noise in audio signal) by applying a [median filter](https://en.wikipedia.org/wiki/Median_filter) or some such on the input before it is fed to the notify pressure observers algorithm? I mean, insert `cpu = med(unfiltered_cpu)` as the first thing in the pseudocode where `med()` is a median filter of an appropriate window size. Should work, right?

Maybe I misunderstood what you meant by fine grained frequency, but let me ask:

Are we aware of important use cases that'd ask for high frequency notification updates? Maybe use cases where e.g. a single dropped frame means a fatal failure? If there are such use cases, maybe a high-frequency mode should be a configuration option? [Rate-limiting change notifications](https://www.w3.org/TR/compute-pressure/#rate-limiting-change-notifications) mitigation would not apply in such cases I believe, so we'd need to think about the privacy impact.


How the system behaved over say the last 10 minutes sounds like an interesting additional input to be fed to the algorithm.

**Comment by anssiko** [comment]
It looks like there's an even better place where to inject this "change threshold exceeded" check: augment step 3 in https://www.w3.org/TR/compute-pressure/#dfn-has-change-in-data

I will submit a PR for this proposal so we can engineer the details there.

**Comment by anssiko** [comment]
Here's the PR with this idea written out in spec terms: https://github.com/w3c/compute-pressure/pull/180
