### ISSUE TITLE
First-party context definition

### ISSUE THREAD

**Issue by anssiko** [w3c/compute-pressure#179]
I noticed "first-party context" concept is not defined by this spec (not a dfn) and is not defined (or not exported) by any other spec. Should that concept be defined here so we could link to it from within this spec? Or should we reconstruct it using the existing concepts defined by other specs?

This concept appears in informative parts of the spec, so maybe we don't need this defined normatively. Opened this issue to see if someone else has ideas. Cc @rakuco.

(Spin off from #157.)

**Comment by rakuco** [comment]
"First-party context" was first mentioned in commit 170389a47951a6c1f5142c7763b684bfe9442516 in the explainer, and was later copied to the spec itself.

I think it would be better to use some existing concepts instead, I just don't know off the top of my head what these would be.

**Comment by anssiko** [comment]
Fixed by #207.
