### ISSUE TITLE
Contributing factors definition needs clarification

### ISSUE THREAD

**Issue by anssiko** [w3c/compute-pressure#181]
According to the current spec text:
- Contributing factors represents the factors contributing to the system performance and current [pressure state](https://www.w3.org/TR/compute-pressure/#dfn-pressure-states).
- The PressureFactor enum represents the [contributing factors](https://www.w3.org/TR/compute-pressure/#dfn-contributing-factors)
- [[Factors]] represents the [contributing factors](https://www.w3.org/TR/compute-pressure/#dfn-contributing-factors)

Contributing factors seems to represent many things and many things also represent contributing factors. I think this could be clarified?

(Spin-off from #180)

Details:

[Contributing factors](https://www.w3.org/TR/compute-pressure/#dfn-contributing-factors) is defined as follows:

>Contributing factors represents the factors contributing to the system performance and current [pressure state](https://www.w3.org/TR/compute-pressure/#dfn-pressure-states).

Contributing factors is referenced in:

[§ 9. Contributing Factors](https://www.w3.org/TR/compute-pressure/#ref-for-dfn-contributing-factors-1)
>The PressureFactor enum represents the [contributing factors](https://www.w3.org/TR/compute-pressure/#dfn-contributing-factors):

```
enum PressureFactor { "thermal", "power-supply" };
```

[§ 10.3 The PressureRecord interface](https://www.w3.org/TR/compute-pressure/#ref-for-dfn-contributing-factors-2)
>a [[Factors]], which is [ordered set](https://infra.spec.whatwg.org/#ordered-set) of [PressureFactor](https://www.w3.org/TR/compute-pressure/#dom-pressurefactor) values, which represents the current [contributing factors](https://www.w3.org/TR/compute-pressure/#dfn-contributing-factors).

[§ 10.6.2 Data delivery](https://www.w3.org/TR/compute-pressure/#ref-for-dfn-contributing-factors-3)
>The data sample and mapping between data sample, and [pressure states](https://www.w3.org/TR/compute-pressure/#dfn-pressure-states) and [contributing factors](https://www.w3.org/TR/compute-pressure/#dfn-contributing-factors) to the current state, is [implementation-defined](https://infra.spec.whatwg.org/#implementation-defined) and may use many different metrics. For instance, for CPU, it might consider processor frequency and utilization, as well as thermal conditions.

**Comment by arskama** [comment]
@anssiko I believe we can close this issue.

1) It has been well defined in:
https://www.w3.org/TR/compute-pressure/#contributing-factors

2) Contributing factors were removed from the specs.

I double checked and I didn't find any conflicts in definitions or usage of the term "Contributnig factors".
