### ISSUE TITLE
Focus control in privacy test steps

### ISSUE THREAD

**Issue by wangw-1991** [w3c/compute-pressure#185]
Let’s consider a special case. As shown in the picture, Main frame A embedded iframe B, iframe B embedded iframe C, iframe C embedded iframe D. Main frame A and iframe C are same -origin, iframe B and iframe D are same-origin, but Main frame A and iframe B are cross-origin. According to the spec, If we focus on iframe B, observer in Iframe D can receive PressureRecord, right? Because top-level browsing context has system (system focus is actually per window, so if the iframe has focus, the top-level browsing context will have system focus) and the document (iframe D) is same-origin with focused document (iframe B).
![image](https://user-images.githubusercontent.com/54053982/217485891-98091ba9-88fd-4daa-8131-58a27fad4207.png)

**Comment by wangw-1991** [comment]
@kenchris @anssiko @rakuco @arskama Hi, all. PTAL, thanks.

**Comment by wangw-1991** [comment]
I checked this in GenericSensor, current focused frame and frames that are same-origin with the current focused frame can get sensor readings.
![image](https://user-images.githubusercontent.com/54053982/217735571-5f867be9-e875-421d-a98a-7d2d7ac300a7.png)

**Comment by arskama** [comment]
As far as I understand the specs, you are correct and I don't see any issue with this.
The question I would ask is: Should them the main frame, be always updated by its own observer even if the embedded iframe as a different origin.
I would say yes, but that is not specified so. (as I understood the specs... :) )
@kenchris @anssiko

**Comment by kenchris** [comment]
I think this is going to be limiting. We want to allow people to embed SDKs like Zoom or Whereby, and we already force them to explicitly set a security polity to allow them to have access. I would say that if they or any parent have focus they should be allowed to have access to the readings

**Comment by wangw-1991** [comment]
So an iframe can access to the readings only when any parent has focus and it is same-origin with the focused parent frame, right?

**Comment by kenchris** [comment]
@anssiko what do you think about this approach?

**Comment by anssiko** [comment]
This, as any other new API, should align with the established practice. I'm hearing the use case at hand is an SDK embedded in an iframe. You can look at how we did that in the Battery Status API for the YT embed.

For novel approaches, I recommend you seek explicit feedback from the relevant horizontal group(s). You can find the in-flight review requests from https://github.com/w3c/compute-pressure/issues/177 and you can augment them with this design consideration. The requests are GH issues filed against each horizontal group's repo.

**Comment by kenchris** [comment]
> Let’s consider a special case. As shown in the picture, Main frame A embedded iframe B, iframe B embedded iframe C, iframe C embedded iframe D. Main frame A and iframe C are same -origin, iframe B and iframe D are same-origin, but Main frame A and iframe B are cross-origin. According to the spec, If we focus on iframe B, observer in Iframe D can receive PressureRecord, right? Because top-level browsing context has system (system focus is actually per window, so if the iframe has focus, the top-level browsing context will have system focus) and the document (iframe D) is same-origin with focused document (iframe B).

According to the spec (as it is written right now), only the focused frame (and anyone same origin with it's origin) can receive events. The frame also has to have all its parents having granted permission policy (auto granted for top level frame)

**Comment by kenchris** [comment]
Let focusedDocument be the topLevelBC's [currently focused area](https://html.spec.whatwg.org/multipage/interaction.html#currently-focused-area-of-a-top-level-browsing-context)'s [node document](https://dom.spec.whatwg.org/#concept-node-document).

// calls this algo:

The currently focused area of a top-level traversable traversable is the [focusable area](https://html.spec.whatwg.org/multipage/interaction.html#focusable-area)-or-null returned by this algorithm:

If traversable does not have [system focus](https://html.spec.whatwg.org/multipage/interaction.html#system-focus), then return null.

Let candidate be traversable's [active document](https://html.spec.whatwg.org/multipage/document-sequences.html#active-document).

While candidate's [focused area](https://html.spec.whatwg.org/multipage/interaction.html#focused-area-of-the-document) is a [navigable container](https://html.spec.whatwg.org/multipage/document-sequences.html#navigable-container) with a non-null [content navigable](https://html.spec.whatwg.org/multipage/document-sequences.html#content-navigable): set candidate to the [active document](https://html.spec.whatwg.org/multipage/document-sequences.html#nav-document) of that [navigable container](https://html.spec.whatwg.org/multipage/document-sequences.html#navigable-container)'s [content navigable](https://html.spec.whatwg.org/multipage/document-sequences.html#content-navigable).

// navigable container == main frame and iframes (and maybe portals in the future) so it iterates to the inner most focused frame

If candidate's [focused area](https://html.spec.whatwg.org/multipage/interaction.html#focused-area-of-the-document) is non-null, set candidate to candidate's [focused area](https://html.spec.whatwg.org/multipage/interaction.html#focused-area-of-the-document).

Return candidate.

**Comment by kenchris** [comment]
Looking over the spec, I think it works as intended. But I think we could discuss whether we should open it up more.

Like currently we try to make sure that only one origin get's data at one time, but maybe it is OK that more do if explicitly allowed by setting security policy

**Comment by wangw-1991** [comment]
> > Let’s consider a special case. As shown in the picture, Main frame A embedded iframe B, iframe B embedded iframe C, iframe C embedded iframe D. Main frame A and iframe C are same -origin, iframe B and iframe D are same-origin, but Main frame A and iframe B are cross-origin. According to the spec, If we focus on iframe B, observer in Iframe D can receive PressureRecord, right? Because top-level browsing context has system (system focus is actually per window, so if the iframe has focus, the top-level browsing context will have system focus) and the document (iframe D) is same-origin with focused document (iframe B).
> 
> According to the spec (as it is written right now), only the focused frame (and anyone same origin with it's origin) can receive events. The frame also has to have all its parents having granted permission policy (auto granted for top level frame)

Yes, permission policy has already been considered. If an iframe is not allowed by permission policy, observer in the frame can't call observe() successfully (see [code](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/compute_pressure/pressure_observer.cc;l=78)). 
There are two issues to be determined：
1. Is cross-origin frame allowed to receive events if permission policy granted? (Is iframe C allowed to receive events if we focus on iframe B?)
2. Does it require any parent has the focus? (Is iframe B allowed to receive events if we focus on iframe D?)

**Comment by kenchris** [comment]
> Is cross-origin frame allowed to receive events if permission policy granted? (Is iframe C allowed to receive events if we focus on iframe B?) This is not allowed in GenericSensor.

Only frame C will get access as well as any other document sharing same-origin

**Comment by kenchris** [comment]
> Do we need to consider the relationship between focused_frame and this_frame? (Is iframe B allowed to receive events if we focus on iframe D? Or is iframe D allowed to receive events if we focus on iframe B?) This is not considered in GenericSensor.

Same as above, only the focused frame (which has allowed policy) and same origin origins can get events

**Comment by arskama** [comment]
@wangw-1991 If you consider this as fixed, please close.
Thanks

**Comment by wangw-1991** [comment]
> @wangw-1991 If you consider this as fixed, please close. Thanks

Thanks for reminding.
