### ISSUE TITLE
Adding document explaining API Surface Changes since last Origin Trial

### ISSUE THREAD

**Issue by arskama** [w3c/compute-pressure#199]
CP API was already proposed during M92-M94 of Chromium:
https://chromestatus.com/feature/5597608644968448

We need to be able to explain to the community, since last Origin Trial, what has changed in the API and why we made the changes.

**Comment by tomayac** [comment]
Made some further improvements in https://github.com/w3c/compute-pressure/commit/cc390e52c251c989c860db11eb18200134716286.
