### ISSUE TITLE
Specify what kind of attacks are considered and addressed

### ISSUE THREAD

**Issue by pes10k** [w3c/compute-pressure#204]
This issue is being filed as part of the [requested PING review](https://github.com/w3cping/privacy-request/issues/113) and was broken off from [this previous issue](https://github.com/w3c/compute-pressure/issues/196)

The section mentions "timing attacks", but this is a very broad term. The text here would be more useful if the text was more precise: what kinds of attacks / timing issues are the authors concerned with and guarding against. My read from the text is that the section is most concerned with different sites observing the same event at the same time, and using that to link browsing contexts. There are other kinds of attacks that requiring timing information to conduct though (e.g., using timing signals to create a side/covert channel). In general, the text here would be improved by being more precise about what kinds of attacks are considered and addressed.

**Comment by anssiko** [comment]
This generic issue was fixed by #216.

The specific proposed attack type dubbed "cross-site covert channel attack" is discussed in #197.
