### ISSUE TITLE
"first party context" section concerns

### ISSUE THREAD

**Issue by pes10k** [w3c/compute-pressure#206]
This issue is being filed as part of the [requested PING review](https://github.com/w3cping/privacy-request/issues/113) and was broken off from [this previous issue](https://github.com/w3c/compute-pressure/issues/196)

The sub-section on "first party contexts" is doubly confusing.

- do the authors mean same domain or same site (i.e., same eTLD+1)? The text uses these terms interchangeably, but they mean different things.
- Is the site restricted to only first-party contexts, or available to first-parties by default, but able to be extended / delegated to third-parties? The first paragraph implies the former, and the second paragraph suggests the latter

**Comment by anssiko** [comment]
With #207 all occurrences of the undefined "first-party context" concept are now replaced with and reconstructed using the following normatively defined concepts:

- Picture-in-Picture: [initiator of an active picture-in-picture-session](https://w3c.github.io/picture-in-picture/#initiators-of-active-picture-in-picture-sessions)
- Media Capture: [context is capturing](https://www.w3.org/TR/mediacapture-streams/#context-is-capturing)
- HTML: [system focus](https://html.spec.whatwg.org/multipage/interaction.html#system-focus), [child navigables](https://html.spec.whatwg.org/multipage/document-sequences.html#child-navigable)

I believe the concern raised in this issue has been addressed, thus I'm closing this issue. Thanks @pes10k for flagging this one and helping remove this undefined concept from the spec that was an unfortunate leftover from the earlier version.

(I've opened #215 to track the same-origin check for workers separately.)
