### ISSUE TITLE
Data delivery and mitigation penalty algorithm issue.

### ISSUE THREAD

**Issue by arskama** [w3c/compute-pressure#229]
While implementing https://www.w3.org/TR/compute-pressure/#data-delivery, step 6.2.1 and 6.2.2, I noticed a missing element in the specs.

Case 1: 
During observationWindowTime, no source is going over the states changeCountThreshold.
The ObservationWindow is then reset. This is ok.

Case 2:
During observationWindowTime, one source is going over the states changeCountThreshold.
The PenaltyTimer is started.
any new record change during penalty is saved into AfterPenaltyRecordMap.
When PenaltyTimer is over,  AfterPenaltyRecordMap(source) record is queued for reporting.

The main issue in Case2, is what to do after Case 2 with the ObservationWindow?
solutionA) Resetting the window, will then hide other "issues" with other sources. For example what if an attackers keeps on attacking source1 (Strong frequency attack)  and source2 (softer frequency attack). Source1 will always take the penalty, but source2 never, because source1 will always reset the window before penalty is triggered on source2. So this doesn't sound like an option.

solutionB) Resetting the ChangeCount[source] after penalty and letting the ObservationWindow finishing its time, is maybe a better solution but it still involves some problems which are not defined in the specs.

What if the penalty is triggered close to the end of the ObservationWindow lifetime and the penalty is longer than the time left in the ObservationWindow.
While taking the penalty, the ObservationWindow will be reset, and if we choose solution B), we will be reseting the countChange of the next ObservationWindow.

I believe Case 2, should be define better in the specs, on what to do with the window and its members in case of penalty.

**Comment by rakuco** [comment]
For more context, this originally came up when we were discussing a problem with a simpler statement: should a source that's reached the count threshold during an observation window continue to trigger the penalty after for the duration of the observation window? In other words, once the threshold is reached the count will only increase, so any new readings after a "penalty window" will trigger it again and again.

**Comment by kenchris** [comment]
Maybe just not increment

>  Increment observer.[[[ChangesCountMap]]](https://www.w3.org/TR/compute-pressure/#dfn-changescountmap)[source].

If observer.[[[AfterPenaltyRecordMap]]](https://www.w3.org/TR/compute-pressure/#dfn-afterpenaltyrecordmap)[source] exists?

Would that work?

**Comment by arskama** [comment]
> I don't think we will need to continuously trigger it, removing some of the readings will already make the mitigation work

I think we agreed on that, or we believe it s the most reasonable solution.

> Maybe just not increment
Not incrementing is still not the solution, will again trigger the penalty because change_count >= change_count_threshold.

I believe the solution is to reset change_count for the penalty source. before scheduling the penalty.
In this way, we do not interfere with the next window in case of overlap between window reset and penalty.

At the same time, the penalty can be carried again later if the count is again reaching the limit.
Other sources penalty can also be detected, since we don't invalidate the window after the first penalty on any source.
