### ISSUE TITLE
Move Options to observe?

### ISSUE THREAD

**Issue by kenchris** [w3c/compute-pressure#259]
If we want to do that, we should do it now.

Spec wise this should be easy

@arskama would this be hard implementation wise?

Do we recall why we move it to the ctor?

ResizeObserver, PerformanceObserver, MutationObserver has it as part of observe:

```js
undefined observe(Node target, optional MutationObserverInit options = {});
undefined observe(Element target, optional ResizeObserverOptions options = {});
undefined observe(optional PerformanceObserverInit options = {});
```

**Comment by kenchris** [comment]
Looks pretty much like we inherited this from when Google was working on this feature:

https://chromium-review.googlesource.com/c/chromium/src/+/2727134/53/third_party/blink/renderer/modules/compute_pressure/compute_pressure_observer.idl

I would say it makes sense to change before shipping

**Comment by arskama** [comment]
Looking at the implementation, I don't see any big changes necessary in the implementation.
Testing code though might have a lot of changes :)
