### ISSUE TITLE
Move source to options

### ISSUE THREAD

**Issue by kenchris** [w3c/compute-pressure#262]
Following up on @Elchi3 's #256 where the following was suggested

```js
await observer.observe({ sources: ["cpu"], sampleInterval: 2500 });
```

This is pretty consistent with PerformanceObserver, the "type" (and "entryTypes") is also part of the options.

We could do 

```js
await observer.observe({ source: "cpu", sampleInterval: 2500 });
```

now (pre shipping), and add `sources` in the future.

Or does @elchi3 believe we should just support `sources` and not `source`?

**Comment by Elchi3** [comment]
I think the reason for `PerformanceObserve` to have both `type` and `entryTypes` is that there are rules about how this plays together with other properties of the options object:

```js
// valid
observe({ type: "resource", buffered: true });
observe({ type: "event", durationThreshold: 160 });
observe({ entryTypes: ["mark", "measure"] });

// invalid
observe({ entryTypes: ["resource"], buffered: true });
observe({ entryTypes: ["event", "mark"], durationThreshold: 160 });
observe({ entryTypes: ["resource"], type: "event" });
```

So in PressureObserver, you need to decide if you want to allow `sampleInterval` to be set for all sources or not, for example, and what would be the deal with source-specific options:

```js
await observer.observe({ sources: ["cpu", "gpu"], sampleInterval: 2500 }); / valid?
await observer.observe({ source: "cpu", sampleInterval: 2500 }); // valid

await observer.observe({ sources: ["cpu", "gpu"], gpuSpecificOption: "foo" }); // invalid?
await observer.observe({ source: "gpu", gpuSpecificOption: "foo" }); // valid
```

> Or does @Elchi3 believe we should just support `sources` and not `source`?

I think I would say having both makes sense. Especially, if you believe there will be source-specific options.

**Comment by kenchris** [comment]
@rakuco do you have any input?

**Comment by kenchris** [comment]
That is exactly what it was modelled after @rakuco I just wanted to make sure that we really thought this through. Maybe PerformanceObserver is a bit of the odd one out here.

I think we are good and should close this.

**Comment by tomayac** [comment]
To be on the safe side, it may be worthwhile to loop in the @w3ctag and hear their opinion on the matter.

**Comment by kenchris** [comment]
True, if the @w3ctag disagree with our reasoning, please reopen
